### PR TITLE
Fix sorting of buckets

### LINKED ISSUE #21: Incorrect tooltip value
In tooltip displayed incorrect value
image

According to graph, the value under mouse is 25, but in tooltip shows 12.
I am using elastic data source

### PR DESCRIPTION
**Pull request by hc4**
fixes #21

### CODE REVIEW

File: src/histogram.js [hunk 1]
```diff
@@ -196,16 +196,16 @@ angular.module('grafana.directives').directive('grafanaHistogram', function($roo
...
-          var bucket = (Math.floor(currentValue / bucketSize)*bucketSize).toFixed(3);
+          var bucket = Math.floor(currentValue / bucketSize) * bucketSize;
           if (bucket in values) {
             values[bucket]++;
           } else {
             values[bucket] = 1;
           }
         }
-        _.forEach(Object.keys(values).sort(), function(key) {
+        for(var key in values) {
```
Comment (mtanda) [inline src/histogram.js:206]: > As I understand dictionary in JS should be sorted by design (at least this is true for Chrome)

I check the behavior, and found that it's not true inf Firefox.
https://jsfiddle.net/fy5tv8ys/2/
